### ISSUE TITLE
v153 issue

### ISSUE THREAD

**Issue by rcon420** [WidovV/cs2-connectionlogs#16]
hey on this build plugin doesnt load could please check whats wrong?

**Comment by WidovV** [comment]
Hey,
I just tried setting it up on a new server and didn't encounter any issues, can you post an error log?

Also check the following:
1. meta command works
2. css command works
3. css version (I tested on v154)
4. The config in `/addons/counterstrikesharp/configs/plugins/ConnectionLogs`

**Comment by WidovV** [comment]
@rcon420 
Is it okay if i close this issue? Or does error(s) still occur?

**Comment by WidovV** [comment]
Issue not provided.
