### ISSUE TITLE
IP logging has stopped last 2 releases.

### ISSUE THREAD

**Issue by AnthonySil** [WidovV/cs2-connectionlogs#3]
Seems like the IP logging has stopped displaying in the last 2 releases. The last successful IP logged for me was 11/25

**Comment by WidovV** [comment]
Hey :D 
I’ll Update it later today

**Comment by WidovV** [comment]
Hey @AnthonySil 
I pushed some new updates, check it out :D
Please note that the config is moved to the default folder :D

**Comment by WidovV** [comment]
Hey, yeah just the 5 files.

Yes, that’s the main config folder, inside of that find /plugins/connectionlogs 

Which errors do you get? :D

**Comment by AnthonySil** [comment]
no errors in counterstrikesharp.log
no config file created in /counterstrikesharp/configs/
no plugin listed when i type "css_plugins" list in console

**Comment by sebastian2510** [comment]
The config is created in /counterstrikesharp/configs/plugins/Connectionlogs.json

However that shouldn't be the cause of the plugin not loading, I try to take a look when i get home :D

**Comment by WidovV** [comment]
The config is created in /counterstrikesharp/configs/plugins/Connectionlogs.json

However that shouldn't be the cause of the plugin not loading, I'll try to take a look when i get home :D

**Comment by WidovV** [comment]
Hey again @AnthonySil 
I cannot not reproduce the plugin to not load and/or not create a config file,
I created a release here: https://github.com/WidovV/cs2-connectionlogs/releases/tag/v0.3 which should be drag and drop
Be sure that the path looks like this: `counterstrikesharp/plugins/ConnectionLogs` which is where those file should be dragged in.

**Comment by WidovV** [comment]
On server restart this folder should appear: `counterstrikesharp/configs/plugins`

**Comment by AnthonySil** [comment]
> On server restart this folder should appear: `counterstrikesharp/configs/plugins/ConnectionLogs`

ya something weird going on, I downloaded these files directly to the server in the same directory as before. restarted the server and i don't see the plugin loading or any errors in the log 

counterstrikesharp.log
[10:13:05.755] [info] CSSharp: Initializing
[10:13:05.755] [info] CSSharp: Globals loaded.
[10:13:05.771] [info] CSSharp: .NET Runtime Initialised.
[10:13:06.160] [info] CSSharp: CounterStrikeSharp.API Loaded Successfully.
[10:13:06.160] [info] CSSharp: Hooks added.

plugins list with current version
meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1]: "Discord Relay" (1.0.0) by K4ryuu

when i restore the previous version
meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 2 plugins loaded.
  [#1]: "Discord Relay" (1.0.0) by K4ryuu
  [#2]: "Connection logs" (0.3) by WidovV
    Logs client connections to a database and discord.


I am running a dedicated server using LinuxGSM version:  v23.7.0 on Operating System: Ubuntu 22.04.3 LTS

**Comment by WidovV** [comment]
Which css version and meta mod version? In any case, try having the newest one

**Comment by AnthonySil** [comment]
im using latest version of CounterStrikeSharp (0.1.0) by Roflmuffin 
and updated Metamod from Metamod:Source version 2.0.0-dev+1256 updated to Metamod:Source version 2.0.0-dev+1275.

but still not loading for me..

**Comment by WidovV** [comment]
Which output do you get when writing css in console? Nothing more, nothing less

**Comment by AnthonySil** [comment]
> Which output do you get when writing css in console? Nothing more, nothing less

css
  CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
  Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison and CS2Fixes.
  See ACKNOWLEDGEMENTS.md for more information.
  Current API Version: 29

**Comment by WidovV** [comment]
Well there’s the issue
Update your css, let me know if you need help with that

**Comment by WidovV** [comment]
You’re around 100 versions behind

**Comment by AnthonySil** [comment]
Hmmm, tried updating css this morning it loaded and is present in the meta list but no plugins load. The css command that i ran earlier is unknown.

I will try again after work.

**Comment by AnthonySil** [comment]
@WidovV  GOT IT! 

I updated CSS with-runtime. I'm not sure if i ever installed the with-runtime build version but its working as expected now. Thanks for all your help appreciate it!
